service: get-by-id-product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  cors: true
  environment:
    PRODUCTS_TABLE: products
    STOCKS_TABLE: stocks

functions:
  hello:
    handler: handler.getProductById
    events:
      - http:
          path: product/{productId}
          method: get
          cors: true