service: create-product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  cors: true
  environment:
    PRODUCTS_TABLE: products
    STOCKS_TABLE: stocks

functions:
  hello:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
