service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  cors: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:PutObject
      - s3:GetObject
    Resource: arn:aws:s3:::import-service-aws/uploaded/*

functions:
  hello:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true

importFileParser:
  handler: importFileParser.handler
  events:
    - s3:
        bucket: import-service-aws
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
          - suffix: .csv
