service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  cors: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:SendMessage
    Resource: arn:aws:s3:::import-service-aws/uploaded/*

functions:
  hello:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true

importFileParser:
  handler: importFileParser.handler
  events:
    - s3:
        bucket: import-service-aws
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
          - suffix: .csv

resources:
  Resources:
    MyImportQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-import-queue
  Outputs:
    MyImportQueueUrl:
      Value:
        Ref: MyImportQueue
      Export:
        Name: MyImportQueueUrl